apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: vps-plagasagricolas-es-project
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source: 
    path: argocd/manifests/certificates/overlay/contabo
    repoURL: https://github.com/manueltortega/contabo-vps-gitops-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true