apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-stop-loss-bot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Enable image updater for this application
    argocd-image-updater.argoproj.io/enable: "false"
    argocd-image-updater.argoproj.io/update-strategy: semver # to apply for all the images
    argocd-image-updater.argoproj.io/image-list: docker.io/josemariasoladuran/crypto-stop-loss-bot
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/github-creds
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:../../base"
    # Disable automatic updates for specific images
    # Uncomment the following line to ignore specific image tags
    # argocd-image-updater.argoproj.io/<image_alias>.ignore-tags: "*"
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: nas-manueltortega-dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-stop-loss-bot
  source: 
    path: argocd/manifests/crypto-stop-loss-bot/overlay/contabo
    repoURL: https://github.com/manueltortega/contabo-vps-gitops-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true