apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vps-plagasagricolas-es-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  # Project description
  description: "Project for VPS Plagas Agricolas ES"
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vps-plagasagricolas-es
  namespace: argocd
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: vps-plagasagricolas-es-project
  destination:
    server: https://kubernetes.default.svc
    namespace: vps-plagasagricolas-es
  source:
    path: argocd/apps
    repoURL: https://github.com/manueltortega/contabo-vps-gitops-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
