apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: vps-jmsola-dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-image-updater
  sources: 
    - chart: argocd-image-updater
      helm:
        values: |
          argocd:
            namespace: argocd
          logLevel: info
          config:
            refresh: 60s
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.12.2
    - path: argocd/manifests/argocd-image-updater/overlay/contabo
      repoURL: https://github.com/jsoladur/contabo-vps-gitops-argocd.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true