apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: vps-jmsola-dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: toolbox
  source: 
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 9.1.11
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true